
name: column-classification-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - timm==1.0.15
      - transformers==4.52.4
      - ultralytics==8.3.152
      - tqdm
      - opencv-python==4.11.0.86
