name: my-env
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - numpy=2.2.4
  - pandas=2.2.3
  - matplotlib=3.10.1
  - scikit-learn=1.6.1
  - opencv=4.11
  - pillow=11.2.1
  - tqdm=4.67.1
  - pip
  - pip:
      - torch==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - timm==1.0.15
      - ultralytics==8.3.135
      - albumentations==2.0.6
      - thop==0.1.1-2209072238
      - pycocotools==2.0.8
