name: my-env
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - opencv
  - pillow
  - tqdm
  - pytorch
  - torchvision
  - pip
  - pip:
      - timm
      - ultralytics
